
package mx.udem.iac.clasificacion.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClasificacionLibrosService", targetNamespace = "urn:library:clasificacion:1.0", wsdlLocation = "file:/private/tmp/claude-501/-Users-jgalvann-UDEM-7mo-03---Integracion-pp-library/9bc2052a-d2d7-494d-a6eb-bed2f330ffea/scratchpad/java-client/library-classiffier.wsdl")
public class ClasificacionLibrosService
    extends Service
{

    private static final URL CLASIFICACIONLIBROSSERVICE_WSDL_LOCATION;
    private static final WebServiceException CLASIFICACIONLIBROSSERVICE_EXCEPTION;
    private static final QName CLASIFICACIONLIBROSSERVICE_QNAME = new QName("urn:library:clasificacion:1.0", "ClasificacionLibrosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/private/tmp/claude-501/-Users-jgalvann-UDEM-7mo-03---Integracion-pp-library/9bc2052a-d2d7-494d-a6eb-bed2f330ffea/scratchpad/java-client/library-classiffier.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASIFICACIONLIBROSSERVICE_WSDL_LOCATION = url;
        CLASIFICACIONLIBROSSERVICE_EXCEPTION = e;
    }

    public ClasificacionLibrosService() {
        super(__getWsdlLocation(), CLASIFICACIONLIBROSSERVICE_QNAME);
    }

    public ClasificacionLibrosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASIFICACIONLIBROSSERVICE_QNAME, features);
    }

    public ClasificacionLibrosService(URL wsdlLocation) {
        super(wsdlLocation, CLASIFICACIONLIBROSSERVICE_QNAME);
    }

    public ClasificacionLibrosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASIFICACIONLIBROSSERVICE_QNAME, features);
    }

    public ClasificacionLibrosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClasificacionLibrosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClasificacionLibrosPortType
     */
    @WebEndpoint(name = "ClasificacionLibrosPort")
    public ClasificacionLibrosPortType getClasificacionLibrosPort() {
        return super.getPort(new QName("urn:library:clasificacion:1.0", "ClasificacionLibrosPort"), ClasificacionLibrosPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClasificacionLibrosPortType
     */
    @WebEndpoint(name = "ClasificacionLibrosPort")
    public ClasificacionLibrosPortType getClasificacionLibrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:library:clasificacion:1.0", "ClasificacionLibrosPort"), ClasificacionLibrosPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASIFICACIONLIBROSSERVICE_EXCEPTION!= null) {
            throw CLASIFICACIONLIBROSSERVICE_EXCEPTION;
        }
        return CLASIFICACIONLIBROSSERVICE_WSDL_LOCATION;
    }

}
