
package mx.udem.iac.clasificacion.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClasificacionLibrosPortType", targetNamespace = "urn:library:clasificacion:1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClasificacionLibrosPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns mx.udem.iac.clasificacion.client.ObtenerConceptosPendientesResponse
     * @throws ErrorDetalleMessage
     */
    @WebMethod(operationName = "ObtenerConceptosPendientes", action = "urn:library:clasificacion:1.0#ObtenerConceptosPendientes")
    @WebResult(name = "ObtenerConceptosPendientesResponse", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
    public ObtenerConceptosPendientesResponse obtenerConceptosPendientes(
        @WebParam(name = "ObtenerConceptosPendientesRequest", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
        ObtenerConceptosPendientesRequest parameters)
        throws ErrorDetalleMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.udem.iac.clasificacion.client.RegistrarClasificacionResponse
     * @throws ErrorDetalleMessage
     */
    @WebMethod(operationName = "RegistrarClasificacion", action = "urn:library:clasificacion:1.0#RegistrarClasificacion")
    @WebResult(name = "RegistrarClasificacionResponse", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
    public RegistrarClasificacionResponse registrarClasificacion(
        @WebParam(name = "RegistrarClasificacionRequest", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
        RegistrarClasificacionRequest parameters)
        throws ErrorDetalleMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.udem.iac.clasificacion.client.ObtenerProgresoUsuarioResponse
     * @throws ErrorDetalleMessage
     */
    @WebMethod(operationName = "ObtenerProgresoUsuario", action = "urn:library:clasificacion:1.0#ObtenerProgresoUsuario")
    @WebResult(name = "ObtenerProgresoUsuarioResponse", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
    public ObtenerProgresoUsuarioResponse obtenerProgresoUsuario(
        @WebParam(name = "ObtenerProgresoUsuarioRequest", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
        ObtenerProgresoUsuarioRequest parameters)
        throws ErrorDetalleMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.udem.iac.clasificacion.client.ObtenerEstadisticasPorModeloResponse
     * @throws ErrorDetalleMessage
     */
    @WebMethod(operationName = "ObtenerEstadisticasPorModelo", action = "urn:library:clasificacion:1.0#ObtenerEstadisticasPorModelo")
    @WebResult(name = "ObtenerEstadisticasPorModeloResponse", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
    public ObtenerEstadisticasPorModeloResponse obtenerEstadisticasPorModelo(
        @WebParam(name = "ObtenerEstadisticasPorModeloRequest", targetNamespace = "urn:library:clasificacion:1.0", partName = "parameters")
        ObtenerEstadisticasPorModeloRequest parameters)
        throws ErrorDetalleMessage
    ;

}
