
package mx.udem.iac.clasificacion.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErrorDetalle", targetNamespace = "urn:library:clasificacion:1.0")
public class ErrorDetalleMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorDetalle faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ErrorDetalleMessage(String message, ErrorDetalle faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ErrorDetalleMessage(String message, ErrorDetalle faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mx.udem.iac.clasificacion.client.ErrorDetalle
     */
    public ErrorDetalle getFaultInfo() {
        return faultInfo;
    }

}
